// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: pix.proto

package pixpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for sending Pix
type SendPixRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount    string `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Recipient string `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
}

func (x *SendPixRequest) Reset() {
	*x = SendPixRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pix_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendPixRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPixRequest) ProtoMessage() {}

func (x *SendPixRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pix_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPixRequest.ProtoReflect.Descriptor instead.
func (*SendPixRequest) Descriptor() ([]byte, []int) {
	return file_pix_proto_rawDescGZIP(), []int{0}
}

func (x *SendPixRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *SendPixRequest) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

// Response message for sending Pix
type SendPixResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransactionId string `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Amount        string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Recipient     string `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Status        string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp     string `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *SendPixResponse) Reset() {
	*x = SendPixResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pix_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendPixResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPixResponse) ProtoMessage() {}

func (x *SendPixResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pix_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPixResponse.ProtoReflect.Descriptor instead.
func (*SendPixResponse) Descriptor() ([]byte, []int) {
	return file_pix_proto_rawDescGZIP(), []int{1}
}

func (x *SendPixResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *SendPixResponse) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *SendPixResponse) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *SendPixResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SendPixResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_pix_proto protoreflect.FileDescriptor

var file_pix_proto_rawDesc = []byte{
	0x0a, 0x09, 0x70, 0x69, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x69, 0x78,
	0x70, 0x62, 0x22, 0x46, 0x0a, 0x0e, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x69, 0x78, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x22, 0xa4, 0x01, 0x0a, 0x0f, 0x53,
	0x65, 0x6e, 0x64, 0x50, 0x69, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25,
	0x0a, 0x0e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x32, 0x46, 0x0a, 0x0a, 0x50, 0x69, 0x78, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x38, 0x0a, 0x07, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x69, 0x78, 0x12, 0x15, 0x2e, 0x70, 0x69, 0x78,
	0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x69, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x70, 0x69, 0x78, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x69,
	0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x70, 0x69, 0x78,
	0x70, 0x62, 0x2f, 0x70, 0x69, 0x78, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pix_proto_rawDescOnce sync.Once
	file_pix_proto_rawDescData = file_pix_proto_rawDesc
)

func file_pix_proto_rawDescGZIP() []byte {
	file_pix_proto_rawDescOnce.Do(func() {
		file_pix_proto_rawDescData = protoimpl.X.CompressGZIP(file_pix_proto_rawDescData)
	})
	return file_pix_proto_rawDescData
}

var file_pix_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pix_proto_goTypes = []interface{}{
	(*SendPixRequest)(nil),  // 0: pixpb.SendPixRequest
	(*SendPixResponse)(nil), // 1: pixpb.SendPixResponse
}
var file_pix_proto_depIdxs = []int32{
	0, // 0: pixpb.PixService.SendPix:input_type -> pixpb.SendPixRequest
	1, // 1: pixpb.PixService.SendPix:output_type -> pixpb.SendPixResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pix_proto_init() }
func file_pix_proto_init() {
	if File_pix_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pix_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendPixRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pix_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendPixResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pix_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pix_proto_goTypes,
		DependencyIndexes: file_pix_proto_depIdxs,
		MessageInfos:      file_pix_proto_msgTypes,
	}.Build()
	File_pix_proto = out.File
	file_pix_proto_rawDesc = nil
	file_pix_proto_goTypes = nil
	file_pix_proto_depIdxs = nil
}
